openapi: 3.1.0
info:
  version: 1.0.0
  title: Admin dashboard API for E-Pharmacy
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of admin dashboard API for E-Pharmacy.
tags:
  - name: Auth
    description: Auth operations.
  - name: Dashboard
    description: Operations about user.
  - name: Orders
    description: Operations about orders.
  - name: Products
    description: Operations about products.
  - name: Suppliers
    description: Operations about suppliers.
  - name: Customers
    description: Operations about customers.
servers:
  - url: https://admin-dashboard-backend-t6zq.onrender.com
paths:
  /api/user/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /api/user/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /api/user/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /api/user/user-info:
    get:
      $ref: ../swagger/paths/auth/user-info.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
